[build]
command = "npm run build"
publish = "public"

[build.environment]
NODE_VERSION = "16"

[build.processing]
  skip_processing = true

# Install dependencies with legacy-peer-deps flag to resolve React conflict
[build.lifecycle]
  onInstall = "npm install --legacy-peer-deps"
